'use client';
import { withIconSize } from '@/shared/lib/withIconSize';
import RawUserIcon from './user.svg';
import RawNotiIcon from './noti.svg';
import RawDarkModeIcon from './darkmode.svg';
import RawLightModeIcon from './lightmode.svg';
import RawDropdownIcon from './dropdown.svg';
import RawErrorIcon from './error.svg';
import RawSuccessIcon from './success.svg';
import RawFilterIcon from './filter.svg';
import RawPinIcon from './pin.svg';
import RawArrowICon from './arrow.svg';
import RawCloseIcon from './close.svg';
import RawLikeIcon from './like.svg';
import RawMeatballsIcon from './meatballs.svg';
import RawEditIcon from './edit.svg';
import RawCancelIcon from './cancel.svg';
import RawDeleteIcon from './delete.svg';
import RawCompleteIcon from './complete.svg';
import RawSelectIcon from './select.svg';
import RawPhotoIcon from './photo.svg';
import RawHelpIcon from './help.svg';
import RawHelpDarkIcon from './help-dark.svg';
import RawHelpInactiveIcon from './help-inactive.svg';
import RawHelpInactiveDarkIcon from './help-inactive-dark.svg';
import RawSearchIcon from './search.svg';
import RawFABDefaultIcon from './fab-default.svg';
import RawAIIcon from './ai.svg';
import RawBookIcon from './book.svg';
import RawChatIcon from './chat.svg';
import RawArrowBack from './arrow-back.svg';
import RawAdd from './add.svg';
import RawSend from './send.svg';
import RawSendReverse from './send-reverse.svg';
import RawRefresh from './refresh.svg';
import RawAddHeart from './add-heart.svg';
import RawNotiTrade from './noti-trade.svg';
import RawAddBook from './add-book.svg';
import RawSwitch from './switch.svg';
import RawSiren from './siren.svg';
import RawInquiry from './inquiry.svg';

import RawAnnouncements from './announcements.svg';
import RawDashboard from './dashboard.svg';
import RawPosts from './posts.svg';
import RawReports from './reports.svg';
import RawUsers from './users.svg';
import RawClock from './clock.svg';

export const UserIcon = withIconSize(RawUserIcon);
export const NotiIcon = withIconSize(RawNotiIcon);
export const DarkModeIcon = withIconSize(RawDarkModeIcon);
export const LightModeIcon = withIconSize(RawLightModeIcon);
export const DropdownIcon = withIconSize(RawDropdownIcon, 20);
export const DropdownIconSm = withIconSize(RawDropdownIcon, 16);
export const ErrorIcon = withIconSize(RawErrorIcon, 50);
export const SuccessIcon = withIconSize(RawSuccessIcon, 50);
export const FilterIcon = withIconSize(RawFilterIcon, 15);
export const PinIcon = withIconSize(RawPinIcon, 20);
export const ArrowICon = withIconSize(RawArrowICon, 20);
export const ArrowIConLg = withIconSize(RawArrowICon, 30);
export const CloseIcon = withIconSize(RawCloseIcon);
export const CloseIconSm = withIconSize(RawCloseIcon, 18);
export const CloseIconXs = withIconSize(RawCloseIcon, 14);
export const AddBook = withIconSize(RawAddBook, 18);

export const LikeIcon = withIconSize(RawLikeIcon);
export const MeatballsIcon = withIconSize(RawMeatballsIcon, 18);
export const EditIcon = withIconSize(RawEditIcon, 18);
export const CancelIcon = withIconSize(RawCancelIcon, 18);
export const DeleteIcon = withIconSize(RawDeleteIcon, 18);
export const CompleteIcon = withIconSize(RawCompleteIcon, 18);
export const SelectIcon = withIconSize(RawSelectIcon);
export const PhotoIcon = withIconSize(RawPhotoIcon, 40);

export const HelpIcon = withIconSize(RawHelpIcon, 18);
export const HelpDarkIcon = withIconSize(RawHelpDarkIcon, 18);
export const HelpInactiveIcon = withIconSize(RawHelpInactiveIcon, 18);
export const HelpInactiveDarkIcon = withIconSize(RawHelpInactiveDarkIcon, 18);
export const SearchIcon = withIconSize(RawSearchIcon);

export const FABDefaultIcon = withIconSize(RawFABDefaultIcon);
export const AIIcon = withIconSize(RawAIIcon, 35);
export const AIIconSm = withIconSize(RawAIIcon, 18);
export const BookIcon = withIconSize(RawBookIcon, 18);
export const ChatIcon = withIconSize(RawChatIcon, 18);
export const SirenIcon = withIconSize(RawSiren, 18);
export const InquiryIcon = withIconSize(RawInquiry, 18);

export const ArrowBackIcon = withIconSize(RawArrowBack, 24);
export const ChatMeatballsIcon = withIconSize(RawMeatballsIcon, 24);
export const AddIcon = withIconSize(RawAdd, 20);
export const SendIcon = withIconSize(RawSend, 18);
export const SendReverseIcon = withIconSize(RawSendReverse, 12);
export const ChatRefreshIcon = withIconSize(RawRefresh, 18);
export const ChatDeleteIcon = withIconSize(RawCloseIcon, 18);
export const AddHeartIcon = withIconSize(RawAddHeart, 18);
export const NotiTradeIcon = withIconSize(RawNotiTrade, 18);
export const SwitchIcon = withIconSize(RawSwitch, 18);

export const AnnouncementsIcon = withIconSize(RawAnnouncements, 18);
export const DashboardIcon = withIconSize(RawDashboard, 18);
export const PostsIcon = withIconSize(RawPosts, 18);
export const ReportsIcon = withIconSize(RawReports, 18);
export const UsersIcon = withIconSize(RawUsers, 18);
export const ClockIconSm = withIconSize(RawClock, 14);
