'use client';
import { withIconSize } from '@/shared/lib/withIconSize';
import RawUserIcon from './user.svg';
import RawNotiIcon from './noti.svg';
import RawDarkModeIcon from './darkmode.svg';
import RawLightModeIcon from './lightmode.svg';
import RawDropdownIcon from './dropdown.svg';
import RawErrorIcon from './error.svg';
import RawSuccessIcon from './success.svg';
import RawFilterIcon from './filter.svg';
import RawPinIcon from './pin.svg';
import RawArrowICon from './arrow.svg';
import RawCloseIcon from './close.svg';
import RawLikeIcon from './like.svg';
import RawMeatballsIcon from './meatballs.svg';
import RawEditIcon from './edit.svg';
import RawCancelIcon from './cancel.svg';
import RawDeleteIcon from './delete.svg';
import RawCompleteIcon from './complete.svg';

export const UserIcon = withIconSize(RawUserIcon);
export const NotiIcon = withIconSize(RawNotiIcon);
export const DarkModeIcon = withIconSize(RawDarkModeIcon);
export const LightModeIcon = withIconSize(RawLightModeIcon);
export const DropdownIcon = withIconSize(RawDropdownIcon, 20);
export const DropdownIconSm = withIconSize(RawDropdownIcon, 16);
export const ErrorIcon = withIconSize(RawErrorIcon, 50);
export const SuccessIcon = withIconSize(RawSuccessIcon, 50);
export const FilterIcon = withIconSize(RawFilterIcon, 15);
export const PinIcon = withIconSize(RawPinIcon, 20);
export const ArrowICon = withIconSize(RawArrowICon, 20);
export const CloseIcon = withIconSize(RawCloseIcon);
export const LikeIcon = withIconSize(RawLikeIcon);
export const MeatballsIcon = withIconSize(RawMeatballsIcon, 18);
export const EditIcon = withIconSize(RawEditIcon, 18);
export const CancelIcon = withIconSize(RawCancelIcon, 18);
export const DeleteIcon = withIconSize(RawDeleteIcon, 18);
export const CompleteIcon = withIconSize(RawCompleteIcon, 18);
